# Generated by Django 4.1.4 on 2022-12-12 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('wine_info', models.CharField(max_length=200)),
                ('alcohol', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('capacity', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
